version: "3"
services:
  redis:
    image: redis:7.4.1-alpine  # O puedes usar una versión específica, como redis:7
    container_name: redis
    ports:
      - "6379:6379"  # Exponer el puerto 6379 del contenedor
    networks:
      - mired  # Asegúrate de que Redis esté en la red correcta
    environment:
      - REDIS_PASSWORD=Qvv3r7y
      # - REDIS_PASSWORD=${REDIS_PASSWORD}  # Usa la contraseña definida en tu .env (si es necesario)
      - REDIS_DB=0  # Definir la base de datos a usar en Redis, por defecto es 0
    # command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Comando para iniciar Redis con contraseña si es necesario
    command: ["redis-server", "--requirepass", "Qvv3r7y"]  # Comando para iniciar Redis con contraseña si es necesario

networks:
  mired:
    external: true  # Asegúrate de que la red externa mired esté creada