services:
  postgres:
    container_name: postgresql-servidor
    image: postgres:16.4-alpine
    networks:
      - mired
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .\data:/var/lib/postgresql/data
networks:
  mired:
    external: true